import Head from 'next/head'
import Image from 'next/image'
import { useDispatch } from 'react-redux'
import { useSelector } from 'react-redux'
import styles from '../../styles/Home.module.css'

export default function Home() {
    const {count} = useSelector((state: any) => state.counter)
    const dispatch = useDispatch()

  return (
    <div className={styles.container}>
      <Head>
        <title>My Redux Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My Redux Store!</a>
        </h1>

       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
